package(default_visibility = ["//visibility:public"])

filegroup(
    name = "STM32H7xx_HAL_Driver_Srcs",
    srcs = glob([
        "Src/*.c",
    ]),
)

filegroup(
    name = "STM32H7xx_HAL_Driver_Hdrs",
    srcs = glob([
        "Inc/*.h",
    ]),
)

#cc_library(
#    name = "STM32H7xx_HAL_Driver",
#    srcs = glob([
#        "Src/*.c",
#    ]),
#    hdrs = glob([
#        "Inc/*.h",
#    ]),
#    includes = ["./Inc"],
#)
