package(
    default_visibility = ["//visibility:public"],
    features = ["warnings_as_errors"],
)

filegroup(
    name = "sources",
    srcs = glob([
        "source/*.c",
    ]),
)

filegroup(
    name = "headers",
    srcs = glob([
        "include/*.h",
    ]),
)
