#pragma once

#include "software/ai/stp/tactic/attacker/attacker_tactic.h"
#include "software/ai/stp/tactic/crease_defender/crease_defender_tactic.h"
#include "software/ai/stp/tactic/dribble/dribble_tactic.h"
#include "software/ai/stp/tactic/get_behind_ball/get_behind_ball_tactic.h"
#include "software/ai/stp/tactic/goalie/goalie_tactic.h"
#include "software/ai/stp/tactic/halt/halt_tactic.h"
#include "software/ai/stp/tactic/kick_or_chip/kick_or_chip_tactic.h"
#include "software/ai/stp/tactic/move/move_tactic.h"
#include "software/ai/stp/tactic/pass_defender/pass_defender_tactic.h"
#include "software/ai/stp/tactic/penalty_kick/penalty_kick_tactic.h"
#include "software/ai/stp/tactic/pivot_kick/pivot_kick_tactic.h"
#include "software/ai/stp/tactic/receiver/receiver_tactic.h"
#include "software/ai/stp/tactic/shadow_enemy/shadow_enemy_tactic.h"
#include "software/ai/stp/tactic/tactic.h"
#include "software/ai/stp/tactic/tactic_base.hpp"
