#pragma once

#include <QtWidgets/QWidget>

#include "software/robot_diagnostics/widgets/slider.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/robot_diagnostics/ui/ui_main_widget.h"

enum class ChargeMode
{
    CHARGE,
    DISCHARGE,
    FLOAT,
};

/**
 * Set up chicker area of the widget
 *
 * @param widget widget to setup
 * @param chicker_power value to modify according to chicker power input
 * @param chicker_autochick value to modify according to chicker autochick mode
 */
void setupChicker(Ui::AutoGeneratedMainWidget *widget, double &chicker_power,
                  bool &chicker_autochick);

/**
 * Set up radio buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerRadioButtons(Ui::AutoGeneratedMainWidget *widget);
