#include "software/robot_diagnostics/widgets/chicker.h"

void setupChicker(Ui::AutoGeneratedMainWidget *widget, double &chicker_power,
                  ChargeMode &charge_mode, ChickerMode &chicker_mode)
{
    setupSliderLineEdit(widget->lineEdit_chicker_power, widget->slider_chicker_power,
                        chicker_power, 0.0, 99.0, 1.0);

    setupChickerRadioButtons(widget, charge_mode, chicker_mode);

    auto chick_pushed = []() {
        // TODO: send some proto
    };

    auto autochick_pushed = []() {
        // TODO: send some proto
    };

    QWidget::connect(widget->pushButton_chick, &QPushButton::clicked, chick_pushed);
    QWidget::connect(widget->pushButton_autochick, &QPushButton::clicked,
                     autochick_pushed);
}

void setupChickerRadioButtons(Ui::AutoGeneratedMainWidget *widget,
                              ChargeMode &charge_mode, ChickerMode &chicker_mode)
{
    widget->radioButton_discharge->setChecked(true);
    widget->radioButton_kicker->setChecked(true);

    auto on_charge_mode_button_changed = [&charge_mode, widget](const bool toggle) {
        if (widget->radioButton_discharge->isChecked())
        {
            charge_mode = ChargeMode::DISCHARGE;
        }
        else if (widget->radioButton_float->isChecked())
        {
            charge_mode = ChargeMode::FLOAT;
        }
        else if (widget->radioButton_charge->isChecked())
        {
            charge_mode = ChargeMode::CHARGE;
        }
    };

    auto on_chicker_mode_button_changed = [&chicker_mode, widget](const bool toggle) {
        if (widget->radioButton_kicker->isChecked())
        {
            chicker_mode = ChickerMode::KICKER;
        }
        else if (widget->radioButton_chipper->isChecked())
        {
            chicker_mode = ChickerMode::CHIPPER;
        }
    };

    QWidget::connect(widget->radioButton_discharge, &QRadioButton::toggled,
                     on_charge_mode_button_changed);
    QWidget::connect(widget->radioButton_float, &QRadioButton::toggled,
                     on_charge_mode_button_changed);
    QWidget::connect(widget->radioButton_charge, &QRadioButton::toggled,
                     on_charge_mode_button_changed);

    QWidget::connect(widget->radioButton_kicker, &QRadioButton::toggled,
                     on_chicker_mode_button_changed);
    QWidget::connect(widget->radioButton_chipper, &QRadioButton::toggled,
                     on_chicker_mode_button_changed);
}
