#pragma once

#include <QtWidgets/QWidget>

#include "software/robot_diagnostics/widgets/slider.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/robot_diagnostics/ui/ui_main_widget.h"

enum class ChargeMode
{
    CHARGE,
    DISCHARGE,
    FLOAT,
};

enum class ChickMode
{
    KICK,
    CHIP,
    AUTOKICK,
    AUTOCHIP,
};

/**
 * Set up chicker area of the widget
 *
 * @param widget widget to setup
 * @param chicker_power value to modify according to chicker power input
 * @param chicker_autochick value to modify according to chicker autochick mode
 */
void setupChicker(Ui::AutoGeneratedMainWidget *widget, double &chicker_power,
                  bool &chicker_autochick);

/**
 * Set up charge radio buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerChargeRadioButtons(Ui::AutoGeneratedMainWidget *widget);

/**
 * Set up autochick radio buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerAutochickRadioButtons(Ui::AutoGeneratedMainWidget *widget);

/**
 * Set up push buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerPushButtons(Ui::AutoGeneratedMainWidget *widget);

/**
 * Set up enabledness of push buttons of the chicker area of the widget
 *
 * @param widget
 * @param enabled
 */
void setChickerPushButtonEnabled(Ui::AutoGeneratedMainWidget *widget, bool enabled);

/**
 * Reset auto chick radio buttons to no auto
 *
 * @param widget
 */
void resetAutochickRadioButtons(Ui::AutoGeneratedMainWidget *widget);
