#include "software/robot_diagnostics/widgets/chicker.h"

void setupChicker(Ui::AutoGeneratedMainWidget *widget, int &chicker_power)
{
    setupSliderLineEdit(widget->lineEdit_chicker_power, widget->slider_chicker_power,
                        chicker_power, 0, 99);
}
