#pragma once

#include <QtWidgets/QWidget>

#include "software/robot_diagnostics/widgets/slider.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/robot_diagnostics/ui/ui_main_widget.h"

enum class ChargeMode
{
    CHARGE,
    DISCHARGE,
    FLOAT,
};

enum class ChickerMode
{
    KICKER,
    CHIPPER,
};

void setupChicker(Ui::AutoGeneratedMainWidget *widget, double &chicker_power,
                  ChargeMode &charge_mode, ChickerMode &chicker_mode);

void setupChickerRadioButtons(Ui::AutoGeneratedMainWidget *widget,
                              ChargeMode &charge_mode, ChickerMode &chicker_mode);
