#include "software/robot_diagnostics/widgets/dribbler.h"

#include <g3log/g3log.hpp>

void setupDribbler(Ui::AutoGeneratedMainWidget *widget, int &dribbler_power)
{
    setupSliderLineEdit(widget->lineEdit_dribbler_power, widget->slider_dribbler_power,
                        dribbler_power, 0, 99);
}
