#pragma once

#include <QtWidgets/QWidget>

#include "software/robot_diagnostics/widgets/slider.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/robot_diagnostics/ui/ui_main_widget.h"

/**
 * Set up dribbler area of the widget
 *
 * @param widget widget to setup
 * @param dribbler_power value to modify according to dribbler power input
 */
void setupDribbler(Ui::AutoGeneratedMainWidget *widget, double &dribbler_power);
