#include "software/robot_diagnostics/widgets/dribbler.h"

void setupDribbler(Ui::AutoGeneratedMainWidget *widget,
                   std::function<void(double)> dribbler_power_changed_callback)
{
    setupSliderLineEdit(widget->lineEdit_dribbler_power, widget->slider_dribbler_power,
                        dribbler_power_changed_callback, 0.0, 99.0, 1.0);

    auto dribbler_stop_pushed = [widget, dribbler_power_changed_callback]() {
        widget->slider_dribbler_power->setValue(0);
        widget->lineEdit_dribbler_power->setText(QString::number(0));

        dribbler_power_changed_callback(0);
    };

    QWidget::connect(widget->pushButton_dribbler_stop, &QPushButton::clicked,
                     dribbler_stop_pushed);
}
