#include "software/robot_diagnostics/widgets/drive.h"

void setupDrive(Ui::AutoGeneratedMainWidget* widget, double& motor_power_fl,
                double& motor_power_fr, double& motor_power_bl, double& motor_power_br,
                double& direct_velocity_x_vel, double& direct_velocity_y_vel,
                double& direct_velocity_angular_vel)
{
    setupSliderLineEdit(widget->lineEdit_motor_fl, widget->slider_motor_fl,
                        motor_power_fl, -100.0, 100.0, 1.0);
    setupSliderLineEdit(widget->lineEdit_motor_fr, widget->slider_motor_fr,
                        motor_power_fr, -100.0, 100.0, 1.0);
    setupSliderLineEdit(widget->lineEdit_motor_bl, widget->slider_motor_bl,
                        motor_power_bl, -100.0, 100.0, 1.0);
    setupSliderLineEdit(widget->lineEdit_motor_br, widget->slider_motor_br,
                        motor_power_br, -100.0, 100.0, 1.0);
    setupSliderLineEdit(widget->lineEdit_direct_velocity_x,
                        widget->slider_direct_velocity_x, direct_velocity_x_vel, -10.0,
                        10.0, 100.0);
    setupSliderLineEdit(widget->lineEdit_direct_velocity_y,
                        widget->slider_direct_velocity_y, direct_velocity_y_vel, -10.0,
                        10.0, 100.0);
    setupSliderLineEdit(widget->lineEdit_direct_velocity_theta,
                        widget->slider_direct_velocity_theta, direct_velocity_angular_vel,
                        -1000.0, 1000.0, 1.0);

    auto direct_per_wheel_stop_pushed = [widget]() {
        // Reset sliders
        widget->lineEdit_motor_fl->setText(QString::number(0));
        widget->slider_motor_fl->setValue(0);
        widget->lineEdit_motor_fr->setText(QString::number(0));
        widget->slider_motor_fr->setValue(0);
        widget->lineEdit_motor_bl->setText(QString::number(0));
        widget->slider_motor_bl->setValue(0);
        widget->lineEdit_motor_br->setText(QString::number(0));
        widget->slider_motor_br->setValue(0);

        // TODO (Issue #1229): send some proto
    };

    auto direct_velocity_stop_pushed = [widget]() {
        // Reset sliders
        widget->lineEdit_direct_velocity_x->setText(QString::number(0));
        widget->slider_direct_velocity_x->setValue(0);
        widget->lineEdit_direct_velocity_y->setText(QString::number(0));
        widget->slider_direct_velocity_y->setValue(0);
        widget->lineEdit_direct_velocity_theta->setText(QString::number(0));
        widget->slider_direct_velocity_theta->setValue(0);

        // TODO (Issue #1229): send some proto
    };

    QWidget::connect(widget->pushButton_direct_per_wheel_stop, &QPushButton::clicked,
                     direct_per_wheel_stop_pushed);
    QWidget::connect(widget->pushButton_direct_velocity_stop, &QPushButton::clicked,
                     direct_velocity_stop_pushed);
}
