#pragma once

#include <QtWidgets/QWidget>

#include "software/robot_diagnostics/widgets/slider.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/robot_diagnostics/ui/ui_main_widget.h"

/**
 * Set up drive area of the widget
 *
 * @param widget widget to setup
 * @param motor_power_fl value to modify according to motor power front left input
 * @param motor_power_fr value to modify according to motor power front right input
 * @param motor_power_bl value to modify according to motor power back left input
 * @param motor_power_br value to modify according to motor power back right input
 * @param matrix_x_vel value to modify according to matrix x velocity input
 * @param matrix_y_vel value to modify according to matrix y velocity input
 * @param matrix_angular_vel value to modify according to matrix angular velocity input
 */
void setupDrive(Ui::AutoGeneratedMainWidget *widget, double motor_power_fl,
                double motor_power_fr, double motor_power_bl, double motor_power_br,
                double matrix_x_vel, double matrix_y_vel, double matrix_angular_vel);
