#include "software/robot_diagnostics/widgets/feedback.h"

void setupFeedback(Ui::AutoGeneratedMainWidget *widget)
{
    setupDribblerTemperature(widget);
}

void setupDribblerTemperature(Ui::AutoGeneratedMainWidget *widget) {}
