#include "software/robot_diagnostics/widgets/feedback.h"

#include <QtWidgets/QComboBox>
#include <QtWidgets/QPushButton>

void setupFeedback(Ui::AutoGeneratedMainWidget *widget)
{
    setupDribblerTemperature(widget);
}

void setupDribblerTemperature(Ui::AutoGeneratedMainWidget *widget) {}
