#pragma once

#include <QtWidgets/QMainWindow>

#include "software/robot_diagnostics/ui/ui_main_widget.h"
#include "software/robot_diagnostics/widgets/feedback.h"

// Forward declare the name of the top-level GUI class defined in main_widget.ui
namespace Ui
{
    class AutoGeneratedMainWidget;
}

class MainWidget : public QMainWindow
{
    Q_OBJECT

   public:
    explicit MainWidget(QWidget* parent = nullptr);

   private:
    // The "parent" of each of these widgets is set during construction, meaning that
    // the Qt system takes ownership of the pointer and is responsible for de-allocating
    // it, so we don't have to
    Ui::AutoGeneratedMainWidget* main_widget;
};

void setupFeedbackDisplay(Ui::AutoGeneratedMainWidget* widget);

void setupDribblerTemperature(Ui::AutoGeneratedMainWidget* widget);
