#include "software/robot_diagnostics/widgets/main_widget.h"

MainWidget::MainWidget(QWidget *parent)
    : QMainWindow(parent), main_widget(new Ui::AutoGeneratedMainWidget())
{
    // Handles all the setup of the generated UI components and adds the components
    // to this widget
    main_widget->setupUi(this);

    // StrongFocus means that the MainWidget will more aggressively capture focus when
    // clicked. Specifically, we do this so that when the user clicks outside of the
    // QLineEdits used for Parameters, the QLineEdit will lose focus.
    // https://www.qtcentre.org/threads/41128-Need-to-implement-in-place-line-edit-unable-to-get-lose-focus-of-QLineEdit
    setFocusPolicy(Qt::StrongFocus);

    setupFeedback(main_widget);
    setupDrive(main_widget, motor_power_fl, motor_power_fr, motor_power_bl,
               motor_power_br, matrix_x_vel, matrix_y_vel, matrix_angular_vel);
    setupDribbler(main_widget, dribbler_power);
    setupChicker(main_widget, chicker_power, charge_mode, chicker_mode);
    setupLEDs(main_widget, led_mode);
    setupRobotSelection(main_widget, robot_selection);

    update();
}
