#include "software/robot_diagnostics/widgets/main_widget.h"

MainWidget::MainWidget(QWidget *parent)
    : QMainWindow(parent), main_widget(new Ui::AutoGeneratedMainWidget())
{
    // Handles all the setup of the generated UI components and adds the components
    // to this widget
    main_widget->setupUi(this);

    // StrongFocus means that the MainWidget will more aggressively capture focus when
    // clicked. Specifically, we do this so that when the user clicks outside of the
    // QLineEdits used for Parameters, the QLineEdit will lose focus.
    // https://www.qtcentre.org/threads/41128-Need-to-implement-in-place-line-edit-unable-to-get-lose-focus-of-QLineEdit
    setFocusPolicy(Qt::StrongFocus);

    dribbler_power_changed_callback = [](double dribbler_power) {
        // TODO (Issue #1229): send some proto
    };

    direct_per_wheel_power_changed_callback =
        [](double direct_per_wheel_power, DirectPerWheelMode direct_per_wheel_mode) {
            // TODO (Issue #1229): send some proto
        };

    direct_velocity_power_changed_callback = [](double direct_per_wheel_power,
                                                DirectVelocityMode direct_velocity_mode) {
        // TODO (Issue #1229): send some proto
    };

    setupFeedback(main_widget);
    setupDrive(main_widget, direct_per_wheel_power_changed_callback,
               direct_velocity_power_changed_callback);
    setupDribbler(main_widget, dribbler_power_changed_callback);
    setupChicker(main_widget, chicker_power, chicker_autochick);
    setupLEDs(main_widget, led_mode);
    setupRobotSelection(main_widget, robot_selection);

    update();
}
