#pragma once

#include <QtWidgets/QWidget>

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/robot_diagnostics/ui/ui_main_widget.h"

/**
 * Sets up slider and line edit linkage and modifies the value as input changes
 * Implements input checking and clamping behaviour
 *
 */
void setupSliderLineEdit(QLineEdit *line_edit, QSlider *slider, double &value, double min,
                         double max, double scaling);
