set(_CATKIN_CURRENT_PACKAGE "corner_kick")
set(corner_kick_VERSION "1.0.0")
set(corner_kick_MAINTAINER "UBC Thunderbots <ubcthunderbots@gmail.com>")
set(corner_kick_PACKAGE_FORMAT "2")
set(corner_kick_BUILD_DEPENDS )
set(corner_kick_BUILD_EXPORT_DEPENDS )
set(corner_kick_BUILDTOOL_DEPENDS "catkin")
set(corner_kick_BUILDTOOL_EXPORT_DEPENDS )
set(corner_kick_EXEC_DEPENDS "rosbridge_server")
set(corner_kick_RUN_DEPENDS "rosbridge_server")
set(corner_kick_TEST_DEPENDS )
set(corner_kick_DOC_DEPENDS )
set(corner_kick_URL_WEBSITE "")
set(corner_kick_URL_BUGTRACKER "")
set(corner_kick_URL_REPOSITORY "")
set(corner_kick_DEPRECATED "")