package(
    default_visibility = ["//software/backend/output/radio/mrf:__subpackages__"],
    features = ["warnings_as_errors"],
)

cc_library(
    name = "util",
    hdrs = [
        "async_operation.h",
        "noncopyable.h",
    ],
    deps = ["@boost//:signals2"],
)
