- double:
    name: speed_scaling_factor
    min: 0.0
    max: 1.0
    value: 0.2
    type: "double"
    description: >-
      The factor to multiply object speed by to determine the length of the velocity
      obstacle in the objects direction of travel.

- double:
    name: robot_obstacle_inflation_factor
    min: 0
    max: 10
    value: 2.0167
    type: "double"
    description: "Factor for robot obstacle size"

