- string:
    name: interface
    value: ""
    description: >-
        The interface to send and receive packets over (can be found through ifconfig)
- string:
    name: logging_dir
    value: ""
    description: >-
        The directory to output logs to. Absolute paths are recommended as the working directory
        is inside the bazel-out directory.
