package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "chicker",
    srcs = ["chicker.py"],
    deps = [
        "//software/thunderscope:constants",
        requirement("pyqtgraph"),
    ],
)
