#!/usr/bin/python3 -B

import os
import sys


def is_cpp_arg(x):
    if x.startswith("-stdc++="):
        return True
    if x == "-Wno-register":
        return True
    if x == "-Wno-sized-deallocation":
        return True

    return False


def strip_cpp_args(input_args):
    return [x for x in input_args if not is_cpp_arg(x)]


def run(path, args):
    os.execv(path, [path] + args[1:])


def main():
    args = sys.argv[:]

    # The ARM GCC has -isystem busted, and forces all headers found
    # through that path to be C only.  Bazel passes all includes as
    # "-isystem", which doesn't interact very well with gcc.  Lets
    # just fix that here.
    args = [(x if x != "-isystem" else "-I") for x in args]

    # Delegate to the C compiler and strip C++ specific options if we are not compiling
    # any .cpp files
    is_a_c_file_present = len(
        [x for x in args
         if x.endswith(".c") or x.endswith(".S")]) > 0

    args.insert(1, "-Wl,--no-as-needed")

    if not is_a_c_file_present:
        run("external/jetson_nano_gcc/bin/aarch64-linux-gnu-gcc", args)
    else:
        run("external/jetson_nano_gcc/bin/aarch64-linux-gnu-gcc", strip_cpp_args(args))


if __name__ == '__main__':
    main()
