package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "graphics_list",
    srcs = ["graphics_list.py"],
    deps = [],
)

py_library(
    name = "extended_gl_view_widget",
    srcs = ["extended_gl_view_widget.py"],
    deps = [
        requirement("pyqtgraph"),
    ],
)
