package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "extended_gl_view_widget",
    srcs = ["extended_gl_view_widget.py"],
    deps = [
        requirement("pyqtgraph"),
    ],
)

py_library(
    name = "observable_list",
    srcs = ["observable_list.py"],
    deps = [],
)

py_library(
    name = "export_to_pytest",
    srcs = ["export_to_pytest.py"],
    deps = [
        requirement("pyqtgraph"),
    ],
)