repos:
-   repo: local
    hooks:
    -   id: compile_pip_requirements
        name: compile pip requirements
        language: system
        entry: scripts/compile_pip_requirements.sh

    -   id: lint_and_format
        name: fix common trivial code errors
        language: system
        entry: scripts/lint_and_format.sh 

    -   id: generate_fsm_diagrams
        name: generate new FSM diagrams
        language: python
        entry: scripts/fsm_diagram_generator.py
