repos:
-   repo: local
    hooks:
    -   id: fix_formatting
        name: fix common trivial code errors
        language: system
        entry: formatting_scripts/fix_formatting.sh 

    -   id: generate_fsm_diagrams
        name: generate new FSM diagrams
        language: python
        entry: ./src/software/ai/fsm_diagram_generator.py
