os: linux
dist: bionic
language: generic

install:
    - ./environment_setup/setup_software.sh

jobs:
  include:
    - name: "Build, Test, and Run Coverage"
      script:
        - cd src
        # Run tests and collect coverage
        - >
          bazel coverage //...     \
            --compilation_mode=fastbuild    \
            --verbose_test_summary          \
            --instrumentation_filter=//...  \
            --test_output=errors
        # Collect Code Coverage Results
        - bash <(curl -s https://codecov.io/bash) -s bazel-testlogs/ | (head -n100 && tail -n100)
        # Build ARM Targets For Firmware
        - bazel build --cpu=stm32h7 //firmware_new/boards/frankie_v1:frankie_v1_main 
        - bazel build --cpu=stm32f4 //firmware/boards/legacy_robot_stm32f4:bin 
        - bazel build --cpu=stm32f4 //firmware/boards/legacy_dongle_stm32f4:bin 
    - name: "Check Formatting"
      script:
        - ./formatting_scripts/check_formatting_ci.sh
