sudo: true
dist: bionic
language: generic

install:
    - ./environment_setup/setup_software.sh

jobs:
  include:
    - name: "Build, Test, and Run Coverage"
      script:
        - cd src
        # Build, test, run coverage
        - >
          bazel coverage //... 
          --compilation_mode=fastbuild 
          --verbose_test_summary 
          --instrumentation_filter=//... 
          --test_output=errors
        # Upload coverage results
        - bash <(curl -s https://codecov.io/bash) -s bazel-testlogs/
        # Build our CPU-specific targets
        - bazel build //firmware_new/... --cpu=stm32h7
    - name: "Check Formatting"
      script:
        - ./clang_format/check_formatting_ci.sh
