sudo: true
dist: bionic
language: generic

install:
    - ./environment_setup/setup_software.sh

jobs:
  include:
    - name: "Build, Test, and Run Coverage"
      script:
        - cd src
        # Build, test, run coverage
        - >
          bazel build //...
          --verbose_test_summary 
          --test_output=errors
        - >
          bazel test //...
          --verbose_test_summary 
          --test_output=errors
        # Build our CPU-specific targets
        - bazel build //firmware_new/... --cpu=stm32h7
    - name: "Check Formatting"
      script:
        - ./clang_format/check_formatting_ci.sh
