os: linux
dist: bionic
language: generic

install:
    - ./environment_setup/setup_software.sh

jobs:
  include:
    - name: "Build and Test some SimulatedTests"
      script:
        - cd src
        # Run tests on only the simulated tests
        - >
            bazel test //software/simulated_tests:shoot_or_pass_play_test
            bazel test //software/simulated_tests:free_kick_play_test
    - name: "Build and Test all SimulatedTests"
      script:
        - cd src
        # Run tests on only the simulated tests
        - >
            bazel test //software/simulated_tests/...
    - name: "Check Formatting"
      script:
        - ./formatting_scripts/check_formatting_ci.sh
