#pragma once

#include <QWidget>

// Forward declare the name of the top-level GUI class defined in main_widget.ui
namespace Ui {
    class MainWidget;
}

/**
 * This class acts as a wrapper widget for all the autogenerated components
 * defined in main_widget.ui
 */
class MainWidget : public QWidget
{
Q_OBJECT

public:
    explicit MainWidget(QWidget *parent = 0);
    ~MainWidget();

private:
    Ui::MainWidget* main_widget;
};
