#pragma once

#include <QWidget>
#include <QGraphicsScene>
#include <QOpenGLWidget>
#include <QGL>
#include "gui/SceneView.h"

// Forward declare the name of the top-level GUI class defined in main_widget.ui
namespace Ui {
    class MainWidget;
}

/**
 * This class acts as a wrapper widget for all the autogenerated components
 * defined in main_widget.ui
 */
class MainWidget : public QWidget
{
Q_OBJECT

public:
    explicit MainWidget(QWidget *parent = 0);
    ~MainWidget();

public slots:
    void drawAI();

private:
    Ui::MainWidget* main_widget;
    QGraphicsScene* scene;
    QOpenGLWidget* glWidget;
    QGLWidget* qglWidget;
    SceneView view;
};
