package(default_visibility = ["//visibility:public"])

py_library(
    name = "proto_configuration_widget",
    srcs = ["proto_configuration_widget.py"],
    deps = [
        "//software/thunderscope/common:build_parameter_tree"
    ]
)

py_library(
    name = "proto_plotter",
    srcs = ["proto_plotter.py"],
    deps = [
        "//software/thunderscope:thread_safe_buffer",
    ],
)

py_library(
    name = "common_widgets",
    srcs = ["common_widgets.py"],
)

py_library(
    name = "build_parameter_tree",
    srcs = ["build_parameter_tree.py"]
)