package(default_visibility = ["//visibility:public"])

py_library(
    name = "proto_configuration_widget",
    srcs = ["proto_configuration_widget.py"],
)

py_library(
    name = "common_widgets",
    srcs = ["common_widgets.py"],
)
