package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "toolbar_icon_loader",
    srcs = ["toolbar_icon_loader.py"],
    data = [
    ],
    deps = [
        requirement("pyqtgraph"),
    ],
)
