cc_library(
    name = "annunciator",
    srcs = ["annunciator.cpp"],
    hdrs = ["annunciator.h"],
    deps = [
        "//software/backend:robot_status",
    ],
)

cc_library(
    name = "dongle",
    srcs = ["dongle.cpp"],
    hdrs = ["dongle.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//software/ai/primitive",
    ],
)
