---
- name: Add user robot to dialout
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - add_user_robot_to_dialout
  ansible.builtin.command: "adduser robot dialout"
  changed_when: true
