---
- name: Copy SSH public key
  block:
    - name: Find SSH public key
      ansible.builtin.stat:
        path: ~/.ssh/id_ed25519.pub
      register: ssh_key_file

    - name: Tell user to make key
      ansible.builtin.debug:
        msg: "Please create an ed25519 SSH key using ssh-keygen"
      when: not ssh_key_file.stat

    - name: Copy SSH public key to robot
      ansible.posix.authorized_key:
        user: robot
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      when: ssh_key_file.stat
