---
- name: Copy SSH key
  block:
    - name: Find SSH key
      ansible.builtin.stat:
        path: ~/.ssh/id_ed25519.pub
      register: SSHfile

    - name: Tell user to make key
      ansible.builtin.debug:
        msg: "Please create an ed25519 SSH key using ssh-keygen"
      when: not SSHfile.stat

    - name: Copy SSH key to robot
      ansible.posix.authorized_key:
        user: robot
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      when: SSHfile.stat
