---
- name: Enable passwordless sudo for rsync
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: EOF
    line: "{{ ansible_user }} ALL=NOPASSWD:/usr/bin/rsync"
