---

- name: enable passwordless sudo for rsync
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: EOF
    line: '{{ ansible_user }} ALL=NOPASSWD:/usr/bin/rsync'
