---
- name: Set up systemd WiFi 5 interface name rule
  become: true
  become_method: sudo
  ansible.posix.synchronize:
    src: ../../linux_configs/systemd/10-persistent-wifi5-net.link
    dest: /etc/systemd/network/
    copy_links: yes

- name: Set up systemd WiFi 6 interface name rule
  become: true
  become_method: sudo
  ansible.posix.synchronize:
    src: ../../linux_configs/systemd/10-persistent-wifi6-net.link
    dest: /etc/systemd/network/
    copy_links: yes
