package(default_visibility = ["//software/gui/visualizer:__subpackages__"])

cc_library(
    name = "geometry_conversion",
    srcs = ["geometry_conversion.cpp"],
    hdrs = ["geometry_conversion.h"],
    deps = [
        "//software/geom",
        "@qt//:qt_core",
        "@qt//:qt_gui",
    ],
)
