package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "sandbox_controls",
    srcs = ["sandbox_controls.py"],
    deps = [
        requirement("pyqtgraph"),
    ],
)
