#pragma once

#include <QtWidgets/QWidget>

#include "software/parameter/dynamic_parameters.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/gui/full_system/ui/ui_main_widget.h"

/**
 * Sets up all the widgets that will be used to control the AI, such as starting or
 * stopping it, or choosing the colour of the friendly team
 */
void setupAIControls(Ui::AutogeneratedFullSystemMainWidget *widget,
                     std::shared_ptr<ThunderbotsConfig> config);

/**
 * Sets up the buttons that will start and top the AI
 */
void setupAIStartAndStopButtons(Ui::AutogeneratedFullSystemMainWidget *widget,
                                std::shared_ptr<ThunderbotsConfig> config);

/**
 * Sets up the ComboBox widget that will be used to select the friendly team colour
 */
void setupTeamColourComboBox(Ui::AutogeneratedFullSystemMainWidget *widget,
                             std::shared_ptr<ThunderbotsConfig> config);

/**
 * Sets up the ComboBox widget that will be used to select the side the friendly team
 * is defending
 */
void setupDefendingSideComboBox(Ui::AutogeneratedFullSystemMainWidget *widget,
                                std::shared_ptr<ThunderbotsConfig> config);

/**
 * Sets up the ComboBox widget that will be used to override the AI GameState
 */
void setupGameStateOverrideComboBox(Ui::AutogeneratedFullSystemMainWidget *widget,
                                    std::shared_ptr<ThunderbotsConfig> config);

/**
 * Sets up the ComboBox widget that will be used to override the current AI Play
 */
void setupPlayOverrideComboBox(Ui::AutogeneratedFullSystemMainWidget *widget,
                               std::shared_ptr<ThunderbotsConfig> config);
