REPLAY_METADATA_DELIMETER = ","
REPLAY_FILE_EXTENSION = "replay"
REPLAY_FILE_TIME_FORMAT = "%Y_%m_%d_%H%M%S"
REPLAY_MAX_CHUNK_SIZE_BYTES = 1024 * 1024  # 1MB

PROTOBUF_BUFFER_SIZE = 1024 * 1024  # 1MB
PLAY_PAUSE_POLL_INTERVAL_SECONDS = 0.1
