package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sources",
    srcs = glob([
        "*.c",
    ]),
)

filegroup(
    name = "headers",
    srcs = glob([
        "include/*.h",
        "*.h",
    ]),
)
