#ifndef PINS_H
#define PINS_H

#include <gpio.h>

extern const gpio_init_pin_t PINS_INIT[4U][16U];

#define PIN_FPGA_PROGRAM_B GPIOB, 11U
#define PIN_FPGA_INIT_B GPIOB, 1U
#define PIN_FPGA_DONE GPIOA, 3U

#define PIN_ICB_CS GPIOB, 10U
#define PIN_ICB_IRQ GPIOB, 0U

#define PIN_POWER_LOGIC GPIOC, 14U
#define PIN_POWER_HV GPIOC, 13U

#define PIN_SD_PRESENT GPIOA, 8U
#define PIN_SD_D0 GPIOC, 8U
#define PIN_SD_D0_EXTI_PORT 2U /* Value to go into SYSCFG_EXTICRn */
#define PIN_SD_D0_EXTI_PIN 8U
#define PIN_SD_D1 GPIOC, 9U
#define PIN_SD_D2 GPIOC, 10U
#define PIN_SD_D3 GPIOC, 11U

#define PIN_OTG_FS_VBUS GPIOA, 9U

#define PIN_BREAKBEAM_LASER GPIOA, 10U

#define PIN_LPS_DRIVE0 GPIOB, 4U
#define PIN_LPS_DRIVE1 GPIOB, 5U
#define PIN_LPS_DRIVE2 GPIOC, 1U
#define PIN_LPS_DRIVE3 GPIOC, 0U

#define PIN_LED_STATUS GPIOB, 13U
#define PIN_LED_LINK GPIOB, 14U
#define PIN_LED_CHARGED GPIOB, 15U

#define PIN_ENCODER0A GPIOA, 15U
#define PIN_ENCODER0B GPIOB, 3U
#define PIN_ENCODER1A GPIOB, 6U
#define PIN_ENCODER1B GPIOB, 7U
#define PIN_ENCODER2A GPIOC, 6U
#define PIN_ENCODER2B GPIOC, 7U
#define PIN_ENCODER3A GPIOA, 0U
#define PIN_ENCODER3B GPIOA, 1U,

#endif
