package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "arb_plot",
    srcs = ["arb_plot.py"],
    deps = [
        requirement("pyqtgraph"),
    ],
)