package(default_visibility = ["//visibility:private"])

filegroup(
    name = "parameter_configs",
    srcs = glob(
        ["**/*.yaml"],
    ),
    visibility = ["//shared/parameter:__subpackages__"],
)
