- double:
    name: immediate_threat_distance
    min: 0.0
    max: 9.5
    value: 6
    description: The distance at which a threat is considered "immediate" if there is only 1 "immediate" threat the defense play will swarm that robot with shadowers
