- double:
    name: goalie_final_speed
    min: 0.0
    max: 3.0
    value: 0.0
    description: >-
      Control the final speed of the goalie to be able to intercept shots better

- double:
    name: ball_speed_panic
    min: 0.0
    max: 6.0
    value: 0.2
    description: >-
      At what speed of the ball should the goalie panic and stop the ball
  
- double:
    name: block_cone_radius
    min: 0.0
    max: 1.0
    value: 0.3
    description: >-
        The radius to wedge the robot into the cone
  
- double:
    name: defense_area_deflation
    min: 0.1
    max: 0.5
    value: 0.2
    description: >-
      How much to deflate the defense area by, larger value means closer to the net
