include:
- ssl_communication_config.yaml
---
- int:
    name: channel
    min: 0
    max: 15
    value: 0
    description: >-
        The multicast channel to join to communicate with the robots
- string:
    name: network_interface
    value: "eth0"
    description: >-
        The network interface that is connected to the thunderbots router.
        Can be found using ifconfig on ubuntu.
