- string:
    name: broken_dribblers
    value: ""
    description: Comma-separated list of numbers of robots with broken dribblers
- string:
    name: broken_chippers
    value: ""
    description: Comma-separated list of numbers of robots with broken chippers
- string:
    name: broken_kickers
    value: ""
    description: Comma-separated list of numbers of robots with broken kickers
