- double:
    name: sliding_friction_acceleration
    min: 0
    max: 10
    value: 0.0
    description: >-
      The scalar friction acceleration in m/s^2 that is applied to the ball 
      while the ball is sliding

- double:
    name: rolling_friction_acceleration
    min: 0
    max: 10
    value: 0.0
    description: >-
      The scalar friction acceleration in m/s^2 that is applied to the ball 
      while the ball is rolling

- double:
    name: ball_restitution
    min: 0
    max: 1.0
    value: 1.0
    description: >-
      The restitution is the amount of energy retained when bouncing off walls and
      robots, 0.0 means perfectly inelastic and 1.0 means perfectly elastic collision.
