- string:
    name: vision_ipv4_address
    value: "224.5.23.2"
    description: The IPv4 address to listen on for vision data
- int:
    name: vision_port
    min: 1
    max: 65535
    value: 10020
    description: The port to listen on for vision data
- string:
    name: game_controller_ipv4_address
    value: "224.5.23.1"
    description: The IPv4 address to listen on for gamecontroller data
- int:
    name: game_controller_port
    min: 1
    max: 65535
    value: 10003
    description: The port to listen on for gamecontroller data

