AIControlConfig:
  RunAI:
    type: "bool"
    default: true
    description: >-
        Selecting will allow HL and Navigator to run, unselecting will
        stop new decisions from being made, but the robots will finish
        the last commands they were given. DO NOT USE in place of the e-stop.
  OverrideAIPlay:
    type: "bool"
    default: false
    description: >-
        Overrides the current play with the play
        specified by currentPlay parameter
  CurrentAIPlay:
    type: "std::string"
    default: "Example Play"
    options:
        - "Example Play"
        - "Stop Play"
        - "Halt Play"
        - "Corner Kick Play"
        - "Free Kick Play"
        - "Defense Play"
        - "KickoffEnemy Play"
        - "KickoffFriendly Play"
        - "Enemy Freekick Play"
        - "Penalty Kick Play"
        - "Penalty Kick Enemy Play"
        - "ShootOrChip Play"
    description: >-
        Specifies the ai play that should be in use
  OverrideRefboxPlay:
    type: "bool"
    default: false
    description: >-
        Overrides the current refbox play with the play
        specified by currentAIPlay parameter
  CurrentRefboxPlay:
    type: "std::string"
    default: "Halt"
    description: >-
        Specifies the refbox play that should be in use
