FullSystemMainCommandLineArgs:
    backend:
        type: "std::string"
        default: ""
        description: >-
            The name of the backend you would like to use. See /software/backend for options
            ex. class WifiBackend this argument would be WifiBackend
    interface:
        type: "std::string"
        default: ""
        description: >-
            The interface to send and receive packets over (can be found through ifconfig)
    headless:
        type: "bool"
        default: False
        description: >-
            Run without the FullSystemGui
    proto_log_output_dir:
        type: "std::string"
        default: ""
        description: >-
            The directory to output logged Protobuf data to. Protobufs will not be logged if this
            argument is not used.
    replay_input_dir:
        type: "std::string"
        default: ""
        description: >-
            The directory to replay logged data from, if the 'replay' backend is selected. This must
            be the `SensorMsg` folder outputted by `proto_log_output_dir`.
    logging_dir:
        type: "std::string"
        default: ""
        description: >-
            The directory to output logs to. Absolute paths are recommended as the working directory
            is inside the bazel-out directory.
