NetworkConfig:
    Channel:
      min: 0
      max: 15
      default: 0
      type: "int"
      description: >-
          The multicast channel to join to communicate with the robots
    NetworkInterface:
      default: "eth0"
      type: "std::string"
      description: >-
          The network interface that is connected to the thunderbots router.
          Can be found using ifconfig on ubuntu.
