NetworkConfig:
    Channel:
      min: 0
      max: 15
      default: 0
      type: "int"
      description: >-
          The multicast channel to join to communicate with the robots
    NetworkInterface:
      default: "eth0"
      type: "std::string"
      description: >-
          The network interface that is connected to the thunderbots router.
          Can be found using ifconfig on ubuntu.
    SSLCommunicationConfig:
      VisionIPv4Address:
        default: "224.5.23.2"
        type: "std::string"
        description: The IPv4 address to listen on for vision data
      VisionPort:
        min: 1
        max: 65535
        default: 10020
        type: "int"
        description: The port to listen on for vision data
      GameControllerIPv4Address:
        default: "224.5.23.1"
        type: "std::string"
        description: The IPv4 address to listen on for gamecontroller data
      GameControllerPort:
        min: 1
        max: 65535
        default: 10003
        type: "int"
        description: The port to listen on for gamecontroller data



