NetworkInputConfig:
  FilterConfig:
    ParticleFilterConfig:
      NumCondensations:
        min: 1
        max: 50
        default: 5
        type: "int"
        description: "The number of condensations for the particle filter"
      TopPercentageOfParticles:
        min: 0
        max: 1
        default: 0.1
        type: "double"
        description: >-
            The top fraction of particles that are used as basepoints for the next 
      MaxDetectionWeight:
        min: 0
        max: 1000
        default: 100
        type: "double"
        description: >- 
            The weight of vision detections
      DetectionWeightDecay:
        min: 0
        max: 10000
        default: 200
        type: "double"
        description: >-
            The decay rate (per meter) of the detection weight
      PreviousBallWeight:
        min: 0
        max: 1000
        default: 1
        type: "double"
        description: >- 
            The weight of the previous ball's position
      PredictionWeight:
        min: 0
        max: 1000
        default: 15
        type: "double"
        description: >- 
            The weight of the previous ball's predicted position
      BallDistThreshold:
        min: 0
        max: 100
        default: 0.5
        type: "double"
        description: >-
            How close a particle must be to the ball to get the extra
      BallConfidenceThreshold:
        min: 0
        max: 100
        default: 60
        type: "double"
        description: >-
            The confidence threshold for being confident or not of the ball's
      BallValidDistThreshold:
        min: 0
        max: 100
        default: 0.1
        type: "double"
        description: >-
            How much the detected ball can move per tick without losing confidence
      BallConfidenceDelta:
        min: 0
        max: 100
        default: 5
        type: "double"
        description: >-
            How much the ball's confidence changes at a time
      BallMaxVariance:
        min: 0
        max: 10
        default: 1
        type: "double"
        description: >-
            The max variance a ball detection can have without losing confidence
