RobotDiagnosticsMainCommandLineArgs:
    backend:
        type: "std::string"
        default: ""
        description: >-
            The name of the backend you would like to use. See /software/backend for options
            ex. class WifiBackend this arugment would be WfiBackend
    interface:
        type: "std::string"
        default: ""
        description: >-
            The interface to send and receive packets over (can be found through ifconfig)
