RobotCapabilitiesConfig:
  BrokenDribblers:
    default: ""
    type: "std::string"
    description: Comma-separated list of numbers of robots with broken dribblers
  BrokenChippers:
    default: ""
    type: "std::string"
    description: Comma-separated list of numbers of robots with broken chippers
  BrokenKickers:
    default: ""
    type: "std::string"
    description: Comma-separated list of numbers of robots with broken kickers
