SimulatedTestMainCommandLineArgs:
    enable_visualizer:
        type: "bool"
        default: false
        description: >-
            Set true to display the simulated test on the visualizer and false to run test internally