package(default_visibility = ["//visibility:public"])

cc_library(
    name = "constants",
    srcs = [],
    hdrs = ["constants.h"],
    deps = [],
)

cc_library(
    name = "firmware_primitive_type",
    hdrs = ["firmware_primitive_type.h"],
)
