package(default_visibility = ["//visibility:public"])

cc_library(
    name = "placeholder_navigator",
    srcs = ["placeholder_navigator.cpp"],
    hdrs = ["placeholder_navigator.h"],
    deps = ["//software/ai/navigator"],
)
