package(default_visibility = ["//visibility:public"])

cc_library(
    name = "dribble_skill",
    hdrs = ["dribble_skill.h"],
)

cc_library(
    name = "pass_skill",
    hdrs = ["pass_skill.h"],
)

cc_library(
    name = "winger_skill",
    hdrs = ["winger_skill.h"],
)

cc_library(
    name = "shoot_skill",
    hdrs = ["shoot_skill.h"],
)
