load("@rules_python//python:pip.bzl", "compile_pip_requirements")

compile_pip_requirements(
    name = "nanopb_requirements",
    src = "nanopb_requirements.in",
    requirements_txt = "nanopb_requirements_lock.txt",
)
