cc_binary(
    name = "frankie_v1",
    srcs = glob([
        "*.c",
        "*.h",
    ]),
    #    deps = [
    #        "//firmware_new/Drivers/STM32H7xx_HAL_Driver:STM32H7xx_HAL_Driver_Hdrs",
    #        "//firmware_new/Drivers/STM32H7xx_HAL_Driver:STM32H7xx_HAL_Driver_Srcs",
    #    ],
)
