package(default_visibility = ["//visibility:public"])

cc_library(
    name = "move_test_tactic",
    srcs = ["move_test_tactic.cpp"],
    hdrs = ["move_test_tactic.h"],
    deps = [
        "//software/ai/hl/stp/action:move_action",
        "//software/ai/hl/stp/tactic",
    ],
)

cc_library(
    name = "stop_test_tactic",
    srcs = ["stop_test_tactic.cpp"],
    hdrs = ["stop_test_tactic.h"],
    deps = [
        "//software/ai/hl/stp/action:stop_action",
        "//software/ai/hl/stp/tactic",
    ],
)

cc_library(
    name = "goalie_test_tactic",
    srcs = ["goalie_test_tactic.cpp"],
    hdrs = ["goalie_test_tactic.h"],
    deps = [
        "//software/ai/hl/stp/tactic",
    ],
)
