package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cmsis",
    hdrs = [
        "cmsis_compiler.h",
        "cmsis_gcc.h",
        "cmsis_version.h",
        "core_cm0.h",
    ]
)
