---

- name: Setting up systemd
  hosts: THUNDERBOTS_HOSTS

  tasks:

    - debug:
        msg: "[Robot ID = {{ inventory_hostname }}]"

    - name: sync binaries to the nano
      with_items:
        - ../../../../../../../../jetson_nano/display
        - ../../../../../../../../jetson_nano/broadcasts
        - ../../../../../../../../jetson_nano/thunderloop_main
        - ../../../../../../../../jetson_nano/redis
      loop_control:
        loop_var: binary_path
      ansible.posix.synchronize:
        src: "{{ binary_path }}"
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - syncBinaries

    - name: sync all systemd files
      become_method: sudo
      become: true
      tags:
        - syncSystemdFiles
      register: res
      ansible.posix.synchronize:
        src: ../../systemd/
        dest: /etc/systemd/system
        copy_links: yes

      #NOTE: "Enabling systems" means they will start on boot
    - name: Enable system services
      become: true
      become_method: sudo
      with_items:
        - thunderbots
        - redis
        - thunderloop
        - display
        - announcement
      loop_control:
        loop_var: service_name
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: yes
        masked: no
        daemon_reload: yes
      tags:
        - enableSystemd

    - name: Reboot
      become: true
      become_user: root
      become_method: sudo
      register: res
      tags:
        - reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 20
        reboot_timeout: 1200
        pre_reboot_delay: 0
        post_reboot_delay: 10
        test_command: whoami
