---

- name: Setting up systemd
  hosts: THUNDERBOTS_HOSTS

  tasks:

    - debug:
        msg: "[Robot ID = {{ inventory_hostname }}]"

    - name: sync binaries to the nano
      with_items:
        - ../../../../../../../../jetson_nano/tftp
        - ../../../../../../../../jetson_nano/display
        - ../../../../../../../../jetson_nano/broadcasts
        - ../../../../../../../../jetson_nano/thunderloop_main
        - ../../../../../../../../jetson_nano/display
      loop_control:
        loop_var: binary_path
      ansible.posix.synchronize:
        src: "{{ binary_path }}"
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - copyBinaries

    - name: sync all relevant systemd files
      become_method: sudo
      become: true
      tags:
        - systemd
        - syncSystemdFiles
      register: res
      ansible.posix.synchronize:
        src: ../../systemd/
        dest: /etc/systemd/system
        copy_links: yes

    - name: Enable path services
      become: true
      become_method: sudo
      with_items:
        - redis_watcher.path
        - tftp_watcher.path
        - thunderloop_watcher.path
        - ui_watcher.path
        - announcement_watcher.path
      loop_control:
        loop_var: service_name
      shell: systemctl enable "{{ service_name }}"
      register: res
      args:
        chdir: /etc/systemd/system
      tags:
        - systemd

      #NOTE: "Enabling systems" means they will start on boot
    - name: Enable system services
      become: true
      become_method: sudo
      with_items:
        - thunderbots
        - redis
        - tftp
        - thunderloop
        - ui
        - announcement
      loop_control:
        loop_var: service_name
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: yes
        masked: no
        daemon_reload: yes
      tags:
        - systemd

    - name: Reboot
      become: true
      become_user: root
      become_method: sudo
      register: res
      tags:
        - reboot
        - systemd
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 20
        reboot_timeout: 1200
        pre_reboot_delay: 0
        post_reboot_delay: 10
        test_command: whoami
