---

- name: Setting up systemd
  hosts: THUNDERBOTS_HOSTS

  tasks:

    - debug:
        msg: "[Robot ID = {{ inventory_hostname }}]"

    - name: sync tftp binaries to the nano
      ansible.posix.synchronize:
        src: ../../../../../../../../jetson_nano/tftp
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - All
        - tftp

    - name: sync display binaries to the nano
      ansible.posix.synchronize:
        src: ../../../../../../../../jetson_nano/display
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - All
        - display

    - name: sync broadcast binaries to the nano
      ansible.posix.synchronize:
        src: ../../../../../../../../jetson_nano/broadcasts
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - All
        - broadcasts

    - name: sync thunderloop binaries to the nano
      ansible.posix.synchronize:
        src: ../../../../../../../../jetson_nano/thunderloop_main
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - All
        - thunderloop
