---

- name: Setting up systemd
  hosts: THUNDERBOTS_HOSTS

  tasks:

    - debug:
        msg: "[Robot ID = {{ inventory_hostname }}]"

      #NOTE: "Enabling systems" means they will start on boot
    - name: Stop Running Binaries
      become: true
      become_method: sudo
      with_items:
        - thunderbots
        - redis
        - thunderloop
        - ui
        - announcement
      loop_control:
        loop_var: service_name
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        masked: no
        daemon_reload: yes
        state: stopped
      tags:
        - flash
        - stopBinaries

    # todo: execute lcd ui (#2443)
    - name: sync new binaries to the nano
      with_items:
        - ../../../../../../../../jetson_nano/display
        - ../../../../../../../../jetson_nano/broadcasts
        - ../../../../../../../../jetson_nano/thunderloop_main
      loop_control:
        loop_var: binary_path
      ansible.posix.synchronize:
        src: "{{ binary_path }}"
        dest: ~/thunderbots_binaries/
        recursive: yes
        copy_links: yes
      tags:
        - syncAllBinaries
        - flash

    - name: start binaries
      become: true
      become_method: sudo
      with_items:
        - thunderbots
        - redis
        - thunderloop
        - ui
        - announcement
      loop_control:
        loop_var: service_name
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        masked: no
        daemon_reload: yes
        state: started
      tags:
        - flash
        - startBinaries


