package(default_visibility = ["//visibility:public"])

cc_library(
    name = "constants",
    srcs = [],
    hdrs = ["constants.h"],
    deps = [],
    alwayslink = True,
)

cc_library(
    name = "robot_constants",
    hdrs = ["robot_constants.h"],
    deps = [
        "//firmware/shared/math:tbots_math",
    ],
)
