package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "mobile_gamepad",
    srcs = ["mobile_gamepad.py"],
    deps = [
        requirement("pygame"),
    ],
)
