load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scoped_timespec_timer",
    srcs = ["scoped_timespec_timer.cpp"],
    hdrs = ["scoped_timespec_timer.h"],
    deps = [],
)
