cc_library(
    name = "parameter",
    srcs = ["parameter.c"],
    hdrs = ["parameter.h"],
)

cc_library(
    name = "example_config",
    srcs = ["example_config.c"],
    hdrs = ["example_config.h"],
    deps = [":parameter"],
)
