package(default_visibility = ["//visibility:public"])

# TODO (#2377): Add Bazel BUILD support for HRVO Python visualizer
# py_binary(
#     name = "hrvo_visualizer",
#     srcs = ["hrvo_visualizer.py"],
#     deps = [
#         requirement("matplotlib"),
#         requirement("pandas"),
#     ],
# )
