package(default_visibility = ["//visibility:public"])

cc_library(
    name = "backend",
    hdrs = ["backend.h"],
    deps = [
        "//software/multithreading:subject",
        "//software/multithreading:threaded_observer",
        "//software/primitive",
        "//software/proto:sensor_msg_cc_proto",
        "//software/world",
    ],
)
