"""
A file of constants that are used throughout the robot UI
"""
# REDIS
REDIS_PORT_NUMBER = 6379

# LCD DISPLAY
BASE_Y = 20
BASE_X = 0
PADDING = 6
CURSOR = ">"

# ROTARY ENCODER
BUTTON_PIN = "UART2_RTS"  # BOARD 40, TEGRA_SOC: 'DAP4_DOUT'
PIN_1 = "DAP4_DIN"  # BOARD 33, TEGRA_SOC: 'GPIO_PE6'
PIN_2 = "DAP4_SCLK"  # BOARD 35, TEGRA_SOC: 'DAP4_FS'

# COLOURS
BLACK = "#000000"
WHITE = "#ffffff"
GREEN = "#00ff00"
RED = "#0000ff"
YELLOW = "#00ffff"
