package(default_visibility = ["//visibility:public"])

cc_library(
    name = "shared",
    srcs = [
        "shared/util.c",
    ],
    hdrs = [
        "shared/constants.h",
        "shared/firmware_primitive_type.h",
        "shared/robot_constants.h",
        "shared/util.h",
    ],
    deps = [],
)
