package(default_visibility = ["//visibility:public"])

load("@display_deps//:requirements.bzl", "requirement")

py_binary(
    name = "rotary_encoder",
    srcs = ["rotary_encoder.py"],
    deps = [requirement("Jetson.GPIO")],
)
