PassingConfig:
  StaticFieldPositionQualityXOffset:
    min: 0
    max: 1
    default: 0.3
    type: "double"
    description: >-
               The offset from the sides of the field to place the rectangular
               sigmoid we use to determine what areas to pass to
  StaticFieldPositionQualityYOffset:
    min: 0
    max: 1
    default: 0.3
    type: "double"
    description: >-
               The offset from the sides of the field to place the rectangular
               sigmoid we use to determine what areas to pass to
  StaticFieldPositionQualityFriendlyGoalDistanceWeight:
    min: 0
    max: 1
    default: 0.3
    type: "double"
    description: >-
        The weight that being close to the goal will have on the static
        position quality. Lower, more negative weights result in the distance
        to the goal having less of an effect.
  EnemyProximityImportance:
    min: 0
    max: 10
    default: 0.5
    type: "double"
    description: >-
               This controls how heavily we weight a robot being near the pass
               receiver when calculating enemy risk to a pass
  IdealMinShootAngleDegrees:
    min: -360
    max: 360
    default: 40
    type: "double"
    description: >-
        The minimum open angle formed by the two enemy goal posts and the
        pass reception position that we think will likely result in a good
        shooting opportunity. Note that we may take shots below this in some
        cases, it's more of a weight then a cutoff.
  IdealMaxRotationToShootDegrees:
    min: 0
    max: 180
    default: 60
    type: "double"
    description: >-
               The maximum angle that we have to rotate after receiving a pass to
               shoot that we think would likely result in a goal. Note that we may
               try to take shots that require us to rotate more then this, it's more
               of a soft limit.
  MinPassSpeedMPerS:
    min: 0
    max: 5
    default: 3.5
    type: "double"
    description: "The minimum pass speed (in m/s)"
  MaxPassSpeedMPerS:
    min: 0
    max: 10
    default: 5.5
    type: "double"
    description: "The maximum pass speed (in m/s)"
  MinTimeOffsetForPassSeconds:
    min: 0
    max: 5
    default: 0.7
    type: "double"
    description: >-
      Minimum time into the future at which the pass should occur. This is
      to ensure we have enough time to setup a robot to actually perform
      the pass. This is in seconds.
  MaxTimeOffsetForPassSeconds:
    min: 0
    max: 5
    default: 4.0
    type: "double"
    description: >-
      Maximum time into the future at which the pass should occur. This gives the
      upper bound on the pass start time, relative to the current time. This is in
      seconds.
  EnemyReactionTime:
    min: 0
    max: 3.0
    default: 0.4
    type: "double"
    description: >-
      How long we think the enemy will take to recognize we're passing and start
      moving to intercept
  NumPassesToOptimize:
    min: 1
    max: 1000
    default: 15
    type: "int"
    description: "The number of passes to try to optimize at any given time"
  NumPassesToKeepAfterPruning:
    min: 0
    max: 1000
    default: 3
    type: "int"
    description: "The number of passes to keep after pruning"
  NumberOfGradientDescentStepsPerIter:
    min: 0
    max: 1000
    default: 10
    type: "int"
    description: "The number of steps of gradient descent to perform in each iteration"
  PassEqualityMaxPositionDifferenceMeters:
    min: 0
    max: 4
    default: 0.05
    type: "double"
    description: >-
      The maximum allowed difference between the reciever and passer
      point of two passes for which they are considered equal
  PassEqualityMaxStartTimeDifferenceSeconds:
    min: 0
    max: 3
    default: 0.1
    type: "double"
    description: "TODO: Add description as part of #149"
  PassEqualityMaxSpeedDifferenceMetersPerSecond:
    min: 0
    max: 4
    default: 0.3
    type: "double"
    description: "TODO: Add description as part of #149"
NavigatorConfig:
  DefaultAvoidDist:
    min: 0
    max: 100
    default: 50
    type: "double"
    description: "TODO: Add description as part of #149"
  CollisionAvoidVelocityScale:
    min: 0
    max: 1
    default: 0.5
    type: "double"
    description: "TODO: Add description as part of #149"
  TransitionSpeedFactor:
    min: 0
    max: 1
    default: 0.6
    type: "double"
    description: "Factor of max speed to use for transition speed calculations"
  VelocityObstacleInflationFactor:
    min: 0
    max: 1
    default: 0.2
    type: "double"
    description: "Factor for velocity obstacle length scaling"
  RobotObstacleInflationFactor:
    min: 0
    max: 10
    default: 1.3
    type: "double"
    description: "Factor for robot obstacle size"
  BallObstacleInflationFactor:
    min: 0
    max: 10
    default: 1.3
    type: "double"
    description: "Factor for ball obstacle size"
RobotExpiryBufferMilliseconds:
  min: 0
  max: 100
  default: 50
  type: "int"
  description: "TODO: Add description as part of #149"
EvaluationConfig:
    PossessionConfig:
      PossessionDist:
        min: 0.0
        max: 1.0
        default: 0.2
        type: "double"
        description: How close the ball has to be to the robot for the robot to have the ball
      PassedToAngleTolerance:
        min: 0.0
        max: 90.0
        default: 15.0
        type: "double"
        description: "angle in degrees that the ball velocity can deviate from the axis between
                      the ball and the robot before it doesn't count as a pass"
      MinPassSpeed:
        min: 0.0
        max: 10.0
        default: 1.0
        type: "double"
        description: minimum speed along the pass axis for it to count as a pass
      PossessionBufferTimeSeconds:
        min: 0.0
        max: 5.0
        default: 1.5
        type: "double"
        description: how far back in time to check if a robot has possession
      PassBufferTimeSeconds:
        min: 0.0
        max: 5.0
        default: 1.0
        type: "double"
        description: how far back in time to check if a robot is receiving a pass
    IndirectChipConfig:
      ChipTargetFraction:
        min: 0.0
        max: 100.0
        default: 0.5
        type: "double"
        description: Adjusts how far between ball and target the robot will chip
      ChipPowerBounceThreshold:
        min: 0.0
        max: 5.0
        default: 0.75
        type: "double"
        description: Maximum fraction of distance between chipper and target the first bounce should be, so ball is rolling when it reaches the target
      MaxChipPower:
        min: 0.0
        max: 100.0
        default: 8.0
        type: "double"
        description: Maximum power the robot can chip the ball at without malfunctions
      ChipTargetAreaInset:
        min: 0.0
        max: 100.0
        default: 0.3
        type: "double"
        description: Closest distance to edge of field that the robot could chip and chase to
      MinChipTriArea:
        min: 0.0
        max: 100.0
        default: 0.5
        type: "double"
        description: Minimum area of chip target triangle
      MinChipTriEdgeLen:
        min: 0.0
        max: 100.0
        default: 0.8
        type: "double"
        description: Minimum edge length of chip target triangle
      MinChipTriEdgeAngle:
        min: 0.0
        max: 180.0
        default: 20
        type: "double"
        description: Minimum angle in degrees between chip triangle edges
      ChipCherryPowerDownscale:
        min: 0.0
        max: 100.0
        default: 0.85
        type: "double"
        description: Percentage of distance to center of triangle to return as target
DefenderCreaseTacticConfig:
  MaxDefenderSeperationDeg:
    min: 0.0
    max: 50
    default: 13.0
    type: "double"
    description: The maximum angle the crease defenders will seperate by, in degrees.
  MinDefenderSeperationDeg:
    min: 0.0
    max: 50
    default: 3.0
    type: "double"
    description: The minimum angle the crease defenders will seperate by, in degrees.
  BallDistForMaxDefenderSeperation:
    min: 0.0
    max: 5
    default: 3
    type: "double"
    description: >-
      The distance between the ball and the defenders at which they will have their
      maximum seperation.
  BallDistForMinDefenderSeperation:
    min: 0.0
    max: 5
    default: 1
    type: "double"
    description: >-
      The distance between the ball and the defenders at which they will have their
      minimum seperation.
PivotActionConfig:
  Experimental:
      type: "bool"
      default: false
      description: If toggled, then loose ball will attempt to pivot with bottom parameters
  ArbScaling:
      min: 0.0
      max: 10.0
      type: "double"
      default: 1.0
      description: How quickly to pivot
  FinishAngleThreshold:
      min: 0.0
      max: 360.0
      type: "double"
      default: 5.0
      description: >-
          How much tolerance in degrees we allow for the final angle before annoucing
          pivot has finished
GoalieTacticConfig:
  BlockConeBuffer:
      min: 0.0
      max: 2.0
      default: 0.0
      type: "double"
      description: >-
        The block cone buffer is the extra distance to add on either side of the robot
        to allow to it be further back in the block cone
  GoalieFinalSpeed:
      min: 0.0
      max: 3.0
      default: 0.0
      type: "double"
      description: >- 
        Control the final speed of the goalie to be able to intercept shots better
  BallSpeedPanic:
      min: 0.0
      max: 6.0
      default: 0.2
      type: "double"
      description: >- 
        At what speed of the ball should the goalie panic and stop the ball
  BlockConeRadius:
      min: 0.0
      max: 1.0
      default: 0.3
      type: "double"
      description: >- 
          The radius to wedge the robot into the cone, defaults to MAXROBOTRADIUS
  DefenseAreaDeflation:
      min: 0.1
      max: 0.5
      default: 0.2
      type: "double"
      description: >- 
        How much to deflate the defense area by, larger value means closer to the
        net
ShootGoalTacticConfig:
  EnemyAboutToStealBallRectangleWidth:
      min: 0.0
      max: 2.0
      type: "double"
      default: 0.18
      description: >-
          The total width ("sideways" of the robot) of the rectangle starting
          from the friendly robot inside which we think an enemy is about to
  EnemyAboutToStealBallRectangleExtensionLength:
      min: 0.0
      max: 2.0
      type: "double"
      default: 0.27
      description: >-
          The total length (in the direction the robot is facing) of the rectangle
          starting from the friendly robot inside which we think an enemy is about to
          steal the ball
RobotCapabilitiesConfig:
  BrokenDribblers:
    default: ""
    type: "std::string"
    description: Comma-separated list of numbers of robots with broken dribblers
  BrokenChippers:
    default: ""
    type: "std::string"
    description: Comma-separated list of numbers of robots with broken chippers
  BrokenKickers:
    default: ""
    type: "std::string"
    description: Comma-separated list of numbers of robots with broken kickers
DefenseShadowEnemyTacticConfig:
  BallStealSpeed:
    default: 0.3
    max: 1.0
    min: 0.0
    type: "double"
    description: Try to steal the passee's ball below this ball speed
CornerKickPlayConfig:
  MaxTimeCommitToPassSeconds:
    min: 0.0
    max: 5.0
    default: 3.0
    type: "double"
    description: The maximum time that we will wait before committing to a pass
ShootOrChipPlayConfig:
  FallbackChipTargetEnemyGoalOffset:
    min: 0.0
    max: 4.0
    default: 1.5
    type: double
    description: >-
      The x offset from the enemy goal for the fallback chip target, ie. where we will
      chip if any enemy approches us before we have a good shot or a robot to chip to
ShootOrPassPlayConfig:
  AbsMinPassScore:
    min: 0.0
    max: 1.0
    default: 0.05
    type: double
    description: The absolute minimum pass quality we're willing to attempt
  PassScoreRampDownDuration:
    min: 0.0
    max: 5.0
    default: 2.0
    type: double
    description: >-
      When we're choosing a pass, we start by looking for a pass with a perfect score
      of 1, and then over time lower the score we're will to accept. This parameter
      how fast we ramp down to absMinPassScore. This is in seconds.
  MinOpenAngleForShotDeg:
    min: 0.0
    max: 90.0
    default: 6
    type: double
    description: The minimum open angle to the goal that we require before taking a shot
ShadowFreekickerTacticConfig:
  RobotSeparationScalingFactor:
    min: 1.0
    max: 5.0
    default: 1.1
    type: double
    description: >-
      How much to scale the separation distance between the two robots shadowing
      an enemy freekicker
HighLevelStrategyConfig:
  UseShootOrPassInsteadOfShootOrChip:
    default: true
    type: bool
    description: Use the ShootOrPassPlay instead of the ShootOrChipPlay
