cameras:
  ignoreCamera_0:
    type: "bool"
    default: false
    description: >-
        Ignores camera 0
  ignoreCamera_1:
    type: "bool"
    default: false
    description: >-
        Ignores camera 1
  ignoreCamera_2:
    type: "bool"
    default: false
    description: >-
        Ignores camera 2
  ignoreCamera_3:
    type: "bool"
    default: false
    description: >-
        Ignores camera 3
