CameraConfig:
  IgnoreCamera_0:
    type: "bool"
    default: false
    description: >-
        Ignores camera 0
  IgnoreCamera_1:
    type: "bool"
    default: false
    description: >-
        Ignores camera 1
  IgnoreCamera_2:
    type: "bool"
    default: false
    description: >-
        Ignores camera 2
  IgnoreCamera_3:
    type: "bool"
    default: false
    description: >-
        Ignores camera 3
