 XBoxControllerDemo:
  robotId:
    min: 0
    max: 16
    default: 0
    type: "int"
    description: "The ID of the robot being controller by the XBox Controller"
  kickSpeedMetersPerSecond:
    min: 0.0
    max: 6.5
    default: 4.0
    type: "double"
    description: "The robot's kick speed in meters per second"
  chipDistanceMeters:
    min: 0.0
    max: 5.0
    default: 1.0
    type: "double"
    description: "How far in meters the robot will chip"
  dribblerRpm:
    min: 0
    max: 10000
    default: 1000
    type: "int"
    description: "The RPM of the robot's dribbler when turned on"
  linearSensitivity:
    min: 0.0
    max: 1.0
    default: 1.0
    type: "double"
    description: >-
        The amount to scale the x and y output values
        by to make the robot more or less sensitive
        to control linearly
  angularSensitivity:
    min: 0.0
    max: 1.0
    default: 1.0
    type: "double"
    description: >-
         The amount to scale the theta output values to
         make the robot more or less sensitive to control
         rotationaly
