package(default_visibility = ["//visibility:public"])

cc_library(
    name = "aabb_tree",
    srcs = [
        "AABB.cc"
    ],
    hdrs = [
        "AABB.h"
    ],
    linkstatic = True,
    deps = [],
)
