package(default_visibility = ["//visibility:public"])

py_library(
    name = "motor_fault_icon_loader",
    srcs = ["motor_fault_icon_loader.py"],
    data = [
        "no_fault.png",
        "stopped.png",
        "warning.png",
    ],
    deps = [],
)
