#pragma once

#include <QtWidgets/QWidget>
#include <memory>

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/gui/robot_diagnostics/ui/ui_main_widget.h"
#include "software/gui/robot_diagnostics/widgets/slider.h"
#include "software/util/make_enum/make_enum.h"

MAKE_ENUM(ChargeMode, CHARGE, DISCHARGE, FLOAT);

MAKE_ENUM(ChickMode, NONE, KICK, CHIP, AUTOKICK, AUTOCHIP);

/**
 * Set up chicker area of the widget
 *
 * @param widget widget to setup
 * @param chicker_state_changed_callback callback for when chicker state input changes
 */
void setupChicker(
    Ui::AutoGeneratedMainWidget *widget,
    std::function<void(double, ChargeMode, ChickMode)> chicker_state_changed_callback);

/**
 * Set up charge radio buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerChargeRadioButtons(Ui::AutoGeneratedMainWidget *widget);

/**
 * Set up autochick radio buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerAutochickRadioButtons(Ui::AutoGeneratedMainWidget *widget);

/**
 * Set up push buttons of the chicker area of the widget
 *
 * @param widget widget to setup
 */
void setupChickerPushButtons(Ui::AutoGeneratedMainWidget *widget);

/**
 * Set up enabledness of push buttons of the chicker area of the widget
 *
 * @param widget
 * @param enabled
 */
void setChickerPushButtonEnabled(Ui::AutoGeneratedMainWidget *widget, bool enabled);

/**
 * Reset auto chick radio buttons to no auto
 *
 * @param widget
 */
void resetAutochickRadioButtons(Ui::AutoGeneratedMainWidget *widget);
