#include "software/gui/robot_diagnostics/widgets/dribbler.h"

#include "shared/constants.h"

void setupDribbler(Ui::AutoGeneratedMainWidget *widget,
                   std::function<void(double)> dribbler_rpm_changed_callback,
                   const RobotConstants_t &robot_constants)
{
    setupSliderLineEdit(widget->lineEdit_dribbler_rpm, widget->slider_dribbler_rpm,
                        dribbler_rpm_changed_callback, 0.0,
                        robot_constants.max_force_dribbler_speed_rpm, 1.0);

    auto dribbler_stop_pushed = [widget, dribbler_rpm_changed_callback]() {
        widget->slider_dribbler_rpm->setValue(0);
        widget->lineEdit_dribbler_rpm->setText(QString::number(0));

        dribbler_rpm_changed_callback(0);
    };

    QWidget::connect(widget->pushButton_dribbler_stop, &QPushButton::clicked,
                     dribbler_stop_pushed);
}
