#pragma once

#include <QtWidgets/QWidget>

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/gui/robot_diagnostics/ui/ui_main_widget.h"
#include "software/gui/robot_diagnostics/widgets/progress_bar.h"
#include "software/proto/sensor_msg.pb.h"

/**
 * Set up feedback area of the widget
 *
 * @param widget widget to setup
 */
void setupFeedback(Ui::AutoGeneratedMainWidget *widget);

/**
 * Update values of components in the feedback widget using a new SensorMsg
 *
 * @param widget the parent widget
 * @param sensor_msg the SensorMsg to update the widget with
 */
void updateFeedback(Ui::AutoGeneratedMainWidget *widget, const SensorMsg &sensor_msg);
