#pragma once

#include <QtWidgets/QWidget>

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/gui/robot_diagnostics/ui/ui_main_widget.h"

/**
 * Set up LED area of the widget
 *
 * @param widget widget to setup
 * @param led_mode value to modify according to led mode input
 */
void setupLEDs(Ui::AutoGeneratedMainWidget *widget, std::string &led_mode);
