#pragma once

#include <QtWidgets/QWidget>

#include "proto/sensor_msg.pb.h"
#include "shared/robot_constants.h"
#include "software/gui/robot_diagnostics/widgets/decimal_progress_bar.h"

// This include is autogenerated by the .ui file in the same folder
// The generated version will be names 'ui_<filename>.h'
#include "software/gui/robot_diagnostics/ui/ui_main_widget.h"

/**
 * Set up status and temperature area of the widget
 *
 * @param widget widget to setup
 * @param robot_constants The robot constants
 */
void setupSensorStatus(Ui::AutoGeneratedMainWidget *widget,
                       const RobotConstants_t &robot_constants);

/**
 * Update values of components in the sensor status widget using a new SensorProto
 *
 * @param widget the parent widget
 * @param sensor_msg the SensorProto to update the widget with
 */
void updateSensorStatus(Ui::AutoGeneratedMainWidget *widget,
                        const SensorProto &sensor_msg);
