package(default_visibility = ["//visibility:public"])

cc_library(
    name = "geometry_conversion",
    srcs = ["geometry_conversion.cpp"],
    hdrs = ["geometry_conversion.h"],
    deps = [
        "//software/geom:all",
        "@qt//:qt_core",
    ],
)
