package(default_visibility = ["//visibility:public"])

cc_library(
    name = "toml_config",
    srcs = ["toml_config_client.cpp"],
    hdrs = ["toml_config_client.h"],
    deps = [
        "//software/logger",
        "@tomlplusplus",
    ],
)
