package(default_visibility = ["//visibility:public"])

cc_test(
    name = "redis_test_cpp",
    srcs = ["redis_test.cpp"],
    deps = [
        "@cpp_redis",
        "//shared/test_util:tbots_gtest_main"
    ],
)
