package(default_visibility = ["//visibility:public"])

cc_library(
    name = "velocity_obstacle",
    hdrs = [
        "velocity_obstacle.h",
    ],
    deps = [
        "//software/geom:vector",
    ],
)
