#include "software/gui/standalone_simulator/widgets/main_widget.h"

#include "software/gui/generic_widgets/world_view/draw_function_visualizer.h"

MainWidget::MainWidget(QWidget* parent)
    : QWidget(parent), main_widget(new Ui::AutoGeneratedMainWidget())
{
    // Handles all the setup of the generated UI components and adds the components
    // to this widget
    main_widget->setupUi(this);

    // Update to make sure all layout changes apply nicely on startup
    update();
}

void MainWidget::draw(const std::vector<DrawFunctionWrapper>& draw_functions)
{
    main_widget->simulation_graphics_view->clearAndDraw(draw_functions);
}

void MainWidget::setViewArea(const Rectangle& view_area)
{
    main_widget->simulation_graphics_view->setViewArea(view_area);
}
