package(default_visibility = ["//software/gui:__subpackages__"])

cc_library(
    name = "parameters_spinbox",
    srcs = ["parameters_spinbox.cpp"],
    hdrs = ["parameters_spinbox.h"],
    deps = [
        "//shared/parameter",
        "//shared/parameter:cpp_configs",
        "//software/logger",
        "//software/util/variant_visitor",
        "@qt//:qt_widgets",
    ],
)
