package(default_visibility = ["//visibility:public"])

cc_library(
    name = "control",
    srcs = ["control.c"],
    hdrs = ["control.h"],
    deps = [
        "//firmware/main/shared:util",
    ],
)
