package(default_visibility = ["//visibility:public"])

cc_library(
    name = "keep_away_tactic",
    srcs = [
        "keep_away_fsm.cpp",
    ],
    hdrs = [
        "keep_away_fsm.h",
    ],
    deps = [
        "//software/ai/evaluation:keep_away",
        "//software/ai/hl/stp/tactic/dribble:dribble_tactic",
    ],
)
