set(_CATKIN_CURRENT_PACKAGE "thunderbots")
set(thunderbots_VERSION "0.0.0")
set(thunderbots_MAINTAINER "UBC Thunderbots <ubcthunderbots@gmail.com>")
set(thunderbots_PACKAGE_FORMAT "2")
set(thunderbots_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "thunderbots_msgs" "dynamic_reconfigure")
set(thunderbots_BUILD_EXPORT_DEPENDS "dynamic_reconfigure")
set(thunderbots_BUILDTOOL_DEPENDS "catkin")
set(thunderbots_BUILDTOOL_EXPORT_DEPENDS )
set(thunderbots_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "thunderbots_msgs" "joy" "dynamic_reconfigure")
set(thunderbots_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "thunderbots_msgs" "joy" "dynamic_reconfigure")
set(thunderbots_TEST_DEPENDS "rostest")
set(thunderbots_DOC_DEPENDS )
set(thunderbots_URL_WEBSITE "")
set(thunderbots_URL_BUGTRACKER "")
set(thunderbots_URL_REPOSITORY "")
set(thunderbots_DEPRECATED "")