macro(generate_cfgs_from_yaml)

    # Run code generator for dynamic reconfigure
    execute_process(
        COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/util/parameter/generate_parameters.py
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/util/parameter/
        )

    # Store autogenerated cfgs
    file(GLOB_RECURSE AUTOGENERATED_CFGS LIST_DIRECTORIES false CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_SOURCE_DIR}/util/parameter/autogenerated/cfg/*.cfg
        )

    # Any change to yaml config folder will reconfigure
    set_property(
        DIRECTORY
        APPEND 
        PROPERTY CMAKE_CONFIGURE_DEPENDS 
        ${CMAKE_CURRENT_SOURCE_DIR}/util/parameter/config
        )

endmacro()
