package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "binary_context_managers",
    srcs = [
        "binary_context_managers.py",
        "full_system.py",
        "game_controller.py",
        "simulator.py",
    ],
)
