name: Environment Setup

on:
  workflow_call:
    inputs: 
      os: 
        required: true
        type: string

runs:
  using: "composite"
  steps:
    # Remove unused packages in the CI runner to free up disk space
    # https://github.com/actions/runner-images/issues/2840
    - name: Free disk space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        echo "${{ runner.os }}"

    - name: Run setup_software.sh
      shell: bash
      if: runner.os == 'x86'
      run: |
        "${GITHUB_WORKSPACE}"/environment_setup/setup_software.sh
    
    - name: Run setup_software_mac.sh
      shell: bash
      if: runner.os == 'arm64'
      run: |
        "${GITHUB_WORKSPACE}"/environment_setup/setup_software_mac.sh
