name: Environment Setup

on:
  workflow_call:
    inputs: 
      os: 
        required: true
        type: string

runs:
  using: "composite"
  steps:
    # Remove unused packages in the CI runner to free up disk space
    # https://github.com/actions/runner-images/issues/2840
    - name: Free disk space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        
    - name: Run setup_software.sh
      shell: bash
      if: runner.os == 'Linux'
      run: |
        "${GITHUB_WORKSPACE}"/environment_setup/setup_software.sh
    
    - name: Run setup_software_mac.sh
      shell: bash
      if: runner.os == 'macOS'
      run: |
        "${GITHUB_WORKSPACE}"/environment_setup/setup_software_mac.sh

    - name: Cache Bazel disk cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/thunderbots_bazel_disk_cache
        key: bazel-cache-${{ runner.os }}-${{ github.job }}-${{ github.sha }}
        restore-keys: |
          bazel-cache-${{ runner.os }}-${{ github.job }}-
          bazel-cache-${{ runner.os }}-

