#!/bin/sh

filter_formattable_files() {
    grep -E '\.(h|cpp|c|cc|hpp|tpp|proto|py|md|yml)$|/BUILD$'
}

toplevel="$(git rev-parse --show-toplevel)"
mtime=$(stat -c %Y "$toplevel/scripts/.last_format_time" 2> /dev/null || echo 0)

git diff --staged --name-only | filter_formattable_files | while read -r file; do
    if [ $mtime -lt "$(stat -c %Y "$toplevel/$file")" ]; then
        # last format invocation was before staged changes
        echo "Please run $toplevel/scripts/lint_and_format.sh before committing!" 1>&2
        exit 1
    fi
done
