package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "error_log_constants",
    srcs = ["error_log_constants.py"],
    data = [
        "crash.png",
        "error_code.png",
        "fatal_log.png",
        "low_battery.png",
    ],
)
