load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "error_log_constants",
    srcs = ["error_log_constants.py"],
    data = [
        "crash.png",
        "error_code.png",
        "fatal_log.png",
        "low_battery.png",
    ],
)
