package(default_visibility = ["//visibility:public"])

cc_library(
    name = "offense_support_tactic",
    srcs = ["offense_support_tactic.cpp"],
    hdrs = ["offense_support_tactic.h"],
    deps = [
        "//software/ai/hl/stp/tactic",
    ],
)
