package(default_visibility = ["//visibility:public"])

py_library(
    name = "config",
    srcs = ["config.py"],
)

py_library(
    name = "hetero_gnn",
    srcs = ["hetero_gnn.py"],
    deps = [
        ":config",
    ],
)
