package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ball_interception_generator",
    srcs = ["ball_interception_generator.cpp"],
    hdrs = ["ball_interception_generator.h"],
    deps = [
        "//software/ai/evaluation:intercept",
        "//software/geom/algorithms",
        "//software/world",
    ],
)
