set(_CATKIN_CURRENT_PACKAGE "thunderbots_msgs")
set(thunderbots_msgs_VERSION "0.0.0")
set(thunderbots_msgs_MAINTAINER "UBC Thunderbots <ubcrobocup@gmail.com>")
set(thunderbots_msgs_PACKAGE_FORMAT "2")
set(thunderbots_msgs_BUILD_DEPENDS "std_msgs" "message_generation")
set(thunderbots_msgs_BUILD_EXPORT_DEPENDS )
set(thunderbots_msgs_BUILDTOOL_DEPENDS "catkin")
set(thunderbots_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(thunderbots_msgs_EXEC_DEPENDS "std_msgs" "message_runtime")
set(thunderbots_msgs_RUN_DEPENDS "std_msgs" "message_runtime")
set(thunderbots_msgs_TEST_DEPENDS )
set(thunderbots_msgs_DOC_DEPENDS )
set(thunderbots_msgs_URL_WEBSITE "")
set(thunderbots_msgs_URL_BUGTRACKER "")
set(thunderbots_msgs_URL_REPOSITORY "")
set(thunderbots_msgs_DEPRECATED "")