package(default_visibility = ["//visibility:public"])

py_library(
    name = "lcd_user_interface",
    srcs = ["lcd_user_interface.py"],
    data = [
        ":tbots_logo"
    ],
)

filegroup(
    name = "tbots_logo",
    srcs = ["tbots.jpg"],
)
