package(default_visibility = ["//visibility:public"])

cc_library(
    name = "radio_output",
    srcs = ["radio_output.cpp"],
    hdrs = ["radio_output.h"],
    deps = [
        "//software/ai/world:ball",
        "//software/ai/world:team",
        "//software/backend:robot_status",
        "//software/backend/output/radio/mrf:dongle"
    ],
)
