cc_library(
    name = "duration",
    srcs = ["duration.cpp"],
    hdrs = ["duration.h"],
    deps = [],
)

cc_library(
    name = "tbots_time",
    srcs = ["tbots_time.cpp"],
    hdrs = ["tbots_time.h"],
    deps = [],
)
