package(default_visibility = ["//visibility:private"])

cc_test(
    name = "move_action_test",
    srcs = ["move_action_test.cpp"],
    deps = [
        "//software/ai/hl/stp/action:move_action",
        "//software/simulated_tests:simulated_action_test_fixture",
        "//software/simulated_tests:simulated_test_main",
        "//software/simulated_tests/validation:validation_function",
        "//software/simulated_tests/validation_functions",
        "//software/test_util",
        "//software/time:duration",
        "//software/world",
    ],
)
