load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "gtest",
    #    build_file = "@//:BUILD",
    #    build_file = "@//:gtest.BUILD",
    #    sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
    strip_prefix = "googletest-release-1.8.1",
    url = "https://github.com/google/googletest/archive/release-1.8.1.zip",
)

http_archive(
    name = "g3log",
    build_file = "@//:g3log.BUILD",
    sha256 = "1c141aa62c30985e8fd8c56bddbf2e32f080bf839a48f53c9593ecdebfb8a175",
    strip_prefix = "g3log-1.3.2",
    url = "https://github.com/KjellKod/g3log/archive/1.3.2.zip",
)
