#ifndef PINS_H
#define PINS_H

#include <gpio.h>

extern const gpio_init_pin_t PINS_INIT[4U][16U];

#define PIN_EMITTER1 GPIOA, 4U
#define PIN_EMITTER2 GPIOA, 5U
#define PIN_EMITTER3 GPIOA, 6U
#define PIN_EMITTER4 GPIOA, 7U

#define PIN_RECEIVER1 GPIOB, 12U
#define PIN_RECEIVER2 GPIOB, 13U
#define PIN_RECEIVER3 GPIOB, 14U
#define PIN_RECEIVER4 GPIOB, 15U

#define PIN_LED_LEFT GPIOB, 0U
#define PIN_LED_RIGHT GPIOB, 1U

#define PIN_BUTTON_SW2 GPIOB, 11U
#define PIN_BUTTON_SW3 GPIOB, 10U

#define PIN_LCD_RS GPIOC, 13U
#define PIN_LCD_RW GPIOC, 14U
#define PIN_LCD_E GPIOC, 15U

#endif

