---
# This file has a bunch of common tasks that can be used individually

- name: Misc tasks (run using --tags)
  hosts: THUNDERBOTS_HOSTS

  tasks:
    # shutsdown a host
    - name: Shutdown
      become_method: ansible.builtin.sudo
      become: true
      ansible.builtin.command: sudo shutdown
      register: res
      changed_when: true
      tags:
        - shutdown
        - never # the never tag is a special Ansible tag. We use it so that tasks do not automatically run unless specifically requested.

    # reboots the host and waits until a connection is re-established
    - name: Reboot
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 20
        reboot_timeout: 1200
        pre_reboot_delay: "00"
        post_reboot_delay: 60
        test_command: whoami
      register: res
      tags:
        - reboot
        - never

    # Outputs computer-robot RTT statistics
    - name: RTT test
      tags:
        - rtt
        - never
      block:
        - name: Extract host ipv4
          ansible.builtin.set_fact:
            ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

        - name: RTT command
          delegate_to: localhost
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              ping -c 10 -w 2 {{ ip }} | tail -1
          register: res
          changed_when: false

    - name: Command Output
      tags:
        - always
      ansible.builtin.debug:
        msg:
          - "[Robot ID = {{ inventory_hostname }}]"
          - "stdout = {{ res.stdout_lines }} "
          - "stderr = {{ res.stderr }}"
          - "{{ var }}"
