package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hl",
    hdrs = ["hl.h"],
    deps = [
        "//software/ai/intent",
        "//proto:play_info_msg_cc_proto",
        "//software/world",
    ],
)
