{
  "gameEventBehavior": {
    "AIMLESS_KICK": "BEHAVIOR_ACCEPT",
    "ATTACKER_DOUBLE_TOUCHED_BALL": "BEHAVIOR_ACCEPT",
    "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
    "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
    "BALL_LEFT_FIELD_GOAL_LINE": "BEHAVIOR_ACCEPT",
    "BALL_LEFT_FIELD_TOUCH_LINE": "BEHAVIOR_ACCEPT",
    "BOT_CRASH_DRAWN": "BEHAVIOR_ACCEPT",
    "BOT_CRASH_UNIQUE": "BEHAVIOR_ACCEPT",
    "BOT_DRIBBLED_BALL_TOO_FAR": "BEHAVIOR_ACCEPT",
    "BOT_HELD_BALL_DELIBERATELY": "BEHAVIOR_ACCEPT",
    "BOT_INTERFERED_PLACEMENT": "BEHAVIOR_ACCEPT",
    "BOT_KICKED_BALL_TOO_FAST": "BEHAVIOR_ACCEPT",
    "BOT_PUSHED_BOT": "BEHAVIOR_ACCEPT",
    "BOT_TIPPED_OVER": "BEHAVIOR_ACCEPT",
    "BOT_TOO_FAST_IN_STOP": "BEHAVIOR_ACCEPT",
    "BOUNDARY_CROSSING": "BEHAVIOR_ACCEPT",
    "DEFENDER_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
    "DEFENDER_TOO_CLOSE_TO_KICK_POINT": "BEHAVIOR_ACCEPT",
    "GOAL": "BEHAVIOR_ACCEPT",
    "INVALID_GOAL": "BEHAVIOR_ACCEPT",
    "KEEPER_HELD_BALL": "BEHAVIOR_ACCEPT",
    "NO_PROGRESS_IN_GAME": "BEHAVIOR_ACCEPT",
    "PENALTY_KICK_FAILED": "BEHAVIOR_ACCEPT",
    "PLACEMENT_SUCCEEDED": "BEHAVIOR_ACCEPT",
    "POSSIBLE_GOAL": "BEHAVIOR_ACCEPT"
  },
  "autoRefConfigs": {
  }
}