package(default_visibility = ["//visibility:public"])

cc_library(
    name = "canvas_messenger",
    srcs = ["canvas_messenger.cpp"],
    hdrs = ["canvas_messenger.h"],
    deps = [
        "//shared:constants",
        "//software/ai/world",
        "//software/util:constants",
    ],
)
