package(default_visibility = ["//visibility:public"])

cc_library(
    name = "navigator",
    hdrs = ["navigator.h"],
    deps = [
        "//software/ai/intent",
        "//software/ai/primitive",
        "//software/ai/world",
    ],
)
