package(default_visibility = ["//visibility:public"])

py_library(
    name = "stats_result",
    srcs = ["stats_result.py"],
    data = [
        "//software:python_bindings.so"
    ]
    deps = [
        "//software/evaluation/logs:event_log"
    ],
)